# -*- coding: utf-8 -*-
"""calculadora1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pkRkfFpher-q5tf85Lk94LRuvDavvP2
"""

print("Calculadora Python \n")
print("Opções de operações matemáticas:")
print("1 - Soma")
print("2 - Subtração")
print("3 - Multiplicação")
print("4 - Divisão\n")
opcao = int(input("Escolha a operação desejada: "))
number1 = float(input("\nAgora digite o primeiro número: "))
number2 = float(input("Agora digite o segundo número: "))

if opcao == 1:
    print("\nSoma: ", number1, "+", number2, "=", number1+number2)
elif opcao == 2:
    print("\nSubtração: ", number1, "-", number2, "=", number1-number2)
elif opcao == 3:
    print("\nMultiplicação: ", number1, "*", number2, "=", number1*number2)
elif opcao == 4:
    try:
        print("\nDivisão: ", number1, "/", number2, "=", number1/number2)
    except:
        if number2 == 0:
            print("\nDivisão: ", number1, "/", number2, "- Operação não pode ser realizada. Justificativa: Denominador é zero")
else:
    print("\nPor favor, digíte uma opção válida!!")

